name: CI Pipeline MLflow to Docker

on:
  push:
    paths:
      - 'MLProject_folder/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install MLflow & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install pandas scikit-learn

      - name: Run MLflow Project
        run: |
          # Mengeksekusi training, BUANG birokrasi Conda dengan --env-manager=local
          mlflow run MLProject_folder/ --env-manager=local

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          # 1. Pengecekan Keamanan Secret
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "ERROR: DOCKER_USERNAME kosong!"
            exit 1
          fi

          # 2. Mengambil Run ID (Presisi Mutlak, mengunci 32 karakter hex asli MLflow)
          RUN_ID=$(ls -1 mlruns/0/ | grep -E '^[a-z0-9]{32}$' | head -n 1)
          echo "Ditemukan Run ID yang valid: $RUN_ID"
          
          # Pengecekan ekstra jika gagal mendapat ID
          if [ -z "$RUN_ID" ]; then
            echo "ERROR: Run ID 32 karakter tidak ditemukan! Pastikan model tersimpan dengan benar."
            exit 1
          fi
          
          # 3. Format nama image diubah otomatis menjadi huruf KECIL semua
          USERNAME=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="$USERNAME/weather-model:latest"
          echo "Membangun Docker Image: $IMAGE_NAME"
          
          # 4. Build image menggunakan MLflow
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n $IMAGE_NAME
          
          # 5. Push image ke Docker Hub
          docker push $IMAGE_NAME
