name: CI Pipeline MLflow to Docker

on:
  push:
    paths:
      - 'MLProject_folder/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install MLflow & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install pandas scikit-learn

      - name: Mengeksekusi training
        run: |
          mlflow run MLProject_folder --experiment-name="Weather_Basic_Experiment" --env-manager=local

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          # 1. Pengecekan Keamanan Secret
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "ERROR: DOCKER_USERNAME kosong!"
            exit 1
          fi

          # 2. RADAR PRESISI TINGGI: Mencari file inti 'MLmodel' di seluruh sudut proyek
          MODEL_DIR=$(find . -name "MLmodel" -exec dirname {} \; | head -n 1)
          echo "Folder model ditemukan di: $MODEL_DIR"
          
          if [ -z "$MODEL_DIR" ]; then
            echo "ERROR: File MLmodel tidak ditemukan! Pastikan skrip training Anda memiliki baris: mlflow.sklearn.log_model(model, 'nama_folder')"
            exit 1
          fi
          
          # Ekstrak Run ID untuk memenuhi Kriteria 3 (Menggunakan Python agar elegan)
          RUN_ID=$(python -c "import mlflow; df=mlflow.search_runs(); print(df['run_id'].iloc[0] if not df.empty else 'Lokal/Manual')")
          echo "Ditemukan Run ID: $RUN_ID"
          
          # 3. Format nama image diubah otomatis menjadi huruf KECIL semua
          USERNAME=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="$USERNAME/weather-model:latest"
          echo "Membangun Docker Image: $IMAGE_NAME"
          
          # 4. Build image menggunakan jalur LOKAL (Tembus langsung, tanpa sistem 'runs:/')
          mlflow models build-docker -m "$MODEL_DIR" -n $IMAGE_NAME
          
          # 5. Push image ke Docker Hubs
          docker push $IMAGE_NAME
